RANGE_NOTE_ON = 128
RANGE_NOTE_OFF = 128
RANGE_VELOCITY = 32
RANGE_TIME_SHIFT = 100

TOKEN_END = RANGE_NOTE_ON + RANGE_NOTE_OFF + RANGE_VELOCITY + RANGE_TIME_SHIFT
TOKEN_PAD = TOKEN_END + 1
VOCAB_SIZE = TOKEN_PAD + 1
TIME_QUANTIZATION_SECONDS = 0.01
